# Generated by Django 6.0.2 on 2026-02-18 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='last_4_digits',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='brokerage_account_type',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='broker_name',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='location',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='billing_day',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='grace_period_days',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='is_capitalized',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='renewal_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='term_months',
        ),
        migrations.AlterField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BankCardAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.asset')),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('last_4_digits', models.CharField(blank=True, max_length=4)),
            ],
            options={
                'verbose_name': 'Bank Card',
                'verbose_name_plural': 'Bank Cards',
            },
            bases=('finance.asset',),
        ),
        migrations.CreateModel(
            name='BrokerageAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.asset')),
                ('broker_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('brokerage_account_type', models.CharField(blank=True, choices=[('BROKERAGE', 'Brokerage'), ('IIS', 'Individual Investment Account'), ('IRA', 'Individual Retirement Account')], max_length=20)),
            ],
            options={
                'verbose_name': 'Brokerage Account',
                'verbose_name_plural': 'Brokerage Accounts',
            },
            bases=('finance.asset',),
        ),
        migrations.CreateModel(
            name='CashAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.asset')),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Cash',
                'verbose_name_plural': 'Cash',
            },
            bases=('finance.asset',),
        ),
        migrations.CreateModel(
            name='CreditCardAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.asset')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('grace_period_days', models.PositiveIntegerField(blank=True, null=True)),
                ('last_4_digits', models.CharField(blank=True, max_length=4)),
                ('billing_day', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Credit Card',
                'verbose_name_plural': 'Credit Cards',
            },
            bases=('finance.asset',),
        ),
        migrations.CreateModel(
            name='DepositAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.asset')),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('term_months', models.PositiveIntegerField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('is_capitalized', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
            },
            bases=('finance.asset',),
        ),
    ]
