# Generated by Django 6.0.2 on 2026-02-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_asset_bank_name_remove_asset_last_4_digits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_balance_calc_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
