# Generated by Django 6.0.2 on 2026-02-20 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_asset_last_balance_calc_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankCardAsset',
            new_name='DebitCardAsset',
        ),
    ]
