# Generated by Django 6.0.2 on 2026-02-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_rename_bankcardasset_to_debitcardasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardasset',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
