# Generated by Django 6.0.2 on 2026-02-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_create_cardasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('DEBIT_CARD', 'Debit Card'), ('DEPOSIT', 'Deposit'), ('CREDIT_CARD', 'Credit Card'), ('BROKERAGE', 'Brokerage Account')], max_length=20),
        ),
    ]
