# Generated by Django 6.0.2 on 2026-02-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_asset_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debitcardasset',
            options={'verbose_name': 'Debit Card', 'verbose_name_plural': 'Debit Cards'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('PRODUCTS', 'Products'), ('CAFE_AND_RESTAURANTS', 'Cafe and restaurants'), ('TRANSPORT', 'Transport'), ('HCS', 'HCS'), ('LEISURE', 'Leisure'), ('CLOTHING_AND_SHOES', 'Clothing and shoes'), ('SPORT', 'Sport'), ('HEALTH_AND_BEAUTY', 'Health and beauty'), ('SUBSCRIPTIONS', 'Subscriptions'), ('TAXES_AND_PENALTIES', 'Taxes and penalties'), ('LEARNING', 'Learning'), ('GIFTS', 'Gifts'), ('TECHNIQUE', 'Technique'), ('TRAVELING', 'Traveling'), ('REALTY', 'Realty'), ('OTHER_WASTE', 'Other waste'), ('SALARY', 'Salary'), ('BONUS', 'Bonus'), ('CASHBACK', 'Cashback'), ('SALE', 'Sale'), ('INVESTMENT', 'Investment'), ('OTHER_REFILL', 'Other refill')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('WASTE', 'Waste'), ('TRANSFER', 'Transfer'), ('REFILL', 'Refill')], max_length=10),
        ),
    ]
