# Generated by Django 6.0.2 on 2026-02-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_debitcardasset_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='balance',
            new_name='initial_balance',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='last_balance_calc_at',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('WASTE', 'Waste'), ('TRANSFER', 'Transfer'), ('REFILL', 'Refill'), ('CHANGING_BALANCE', 'Changing Balance')], max_length=20),
        ),
    ]
