# Generated by Django 6.0.2 on 2026-02-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_rename_balance_asset_initial_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='initial_balance',
        ),
    ]
