# Generated by Django 6.0.2 on 2026-02-22 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_remove_asset_initial_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingAccount',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.asset')),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Saving Account',
                'verbose_name_plural': 'Saving Accounts',
            },
            bases=('finance.asset',),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('DEBIT_CARD', 'Debit Card'), ('DEPOSIT', 'Deposit'), ('CREDIT_CARD', 'Credit Card'), ('BROKERAGE', 'Brokerage Account'), ('SAVING_ACCOUNT', 'Saving Account')], max_length=20),
        ),
    ]
