# Generated by Django 6.0.2 on 2026-02-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_savingaccount_alter_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositasset',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('DEBIT_CARD', 'Debit Card'), ('CREDIT_CARD', 'Credit Card'), ('DEPOSIT', 'Deposit'), ('SAVING_ACCOUNT', 'Saving Account'), ('BROKERAGE', 'Brokerage Account')], max_length=20),
        ),
    ]
