# Generated by Django 6.0.2 on 2026-03-08 10:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_depositasset_bank_name_savingaccount_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='from_asset_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_asset_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('PRODUCTS', 'Products'), ('CAFE_AND_RESTAURANTS', 'Cafe and restaurants'), ('TRANSPORT', 'Transport'), ('HCS', 'HCS'), ('HOUSEHOLD', 'Household'), ('PERSONAL', 'Personal'), ('LEISURE', 'Leisure'), ('ENTERTAINMENT', 'Entertainment'), ('CLOTHING_AND_SHOES', 'Clothing and shoes'), ('SPORT', 'Sport'), ('HEALTH_AND_BEAUTY', 'Health and beauty'), ('SUBSCRIPTIONS', 'Subscriptions'), ('TAXES_AND_PENALTIES', 'Taxes and penalties'), ('LEARNING', 'Learning'), ('GIFTS', 'Gifts'), ('TECHNIQUE', 'Technique'), ('TRAVELING', 'Traveling'), ('REALTY', 'Realty'), ('OTHER_WASTE', 'Other waste'), ('SALARY', 'Salary'), ('BONUS', 'Bonus'), ('CASHBACK', 'Cashback'), ('INTEREST', 'Interest'), ('SALE', 'Sale'), ('INVESTMENT', 'Investment'), ('OTHER_REFILL', 'Other refill')], max_length=30),
        ),
    ]
