# Generated by Django 6.0.2 on 2026-03-08 11:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_transaction_from_asset_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='commission_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5),
        ),
    ]
