# Generated by Django 6.0.2 on 2026-03-22 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_transaction_commission_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EWalletAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.asset')),
                ('provider_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'E-Wallet',
                'verbose_name_plural': 'E-Wallets',
            },
            bases=('finance.asset',),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('DEBIT_CARD', 'Debit Card'), ('CREDIT_CARD', 'Credit Card'), ('DEPOSIT', 'Deposit'), ('SAVING_ACCOUNT', 'Saving Account'), ('E_WALLET', 'E-Wallet'), ('BROKERAGE', 'Brokerage Account')], max_length=20),
        ),
    ]
