# Generated by Django 6.0.2 on 2026-03-28 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_invitationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banks/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='creditcardasset',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='debitcardasset',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='depositasset',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='savingaccount',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='creditcardasset',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assets', to='finance.bank'),
        ),
        migrations.AddField(
            model_name='debitcardasset',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assets', to='finance.bank'),
        ),
        migrations.AddField(
            model_name='depositasset',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assets', to='finance.bank'),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assets', to='finance.bank'),
        ),
    ]
