# Generated by Django 6.0.2 on 2026-03-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_add_bank_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='commission_type',
            field=models.CharField(choices=[('PERCENT', 'Percent'), ('ABSOLUTE', 'Absolute')], default='PERCENT', max_length=10),
        ),
    ]
