# Generated by Django 6.0.2 on 2026-03-28 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ewalletasset',
            name='provider_name',
        ),
        migrations.AddField(
            model_name='ewalletasset',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assets', to='finance.provider'),
        ),
    ]
