# Generated by Django 6.0.2 on 2026-03-29 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_remove_ewalletasset_provider_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='cashback_categories_limit',
            field=models.PositiveIntegerField(default=3, help_text='Number of cashback categories user can select for this bank'),
        ),
        migrations.CreateModel(
            name='BankCashbackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PRODUCTS', 'Products'), ('CAFE_AND_RESTAURANTS', 'Cafe and restaurants'), ('TRANSPORT', 'Transport'), ('HCS', 'HCS'), ('HOUSEHOLD', 'Household'), ('PERSONAL', 'Personal'), ('LEISURE', 'Leisure'), ('ENTERTAINMENT', 'Entertainment'), ('CLOTHING_AND_SHOES', 'Clothing and shoes'), ('SPORT', 'Sport'), ('HEALTH_AND_BEAUTY', 'Health and beauty'), ('SUBSCRIPTIONS', 'Subscriptions'), ('TAXES_AND_PENALTIES', 'Taxes and penalties'), ('LEARNING', 'Learning'), ('GIFTS', 'Gifts'), ('TECHNIQUE', 'Technique'), ('TRAVELING', 'Traveling'), ('REALTY', 'Realty'), ('ONLINE_STORES', 'Online stores'), ('APPS_AND_GAMES', 'Apps and games'), ('OTHER', 'Other')], max_length=30)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('limit', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly limit for this category', max_digits=15, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_categories', to='finance.bank')),
            ],
            options={
                'ordering': ['category'],
                'unique_together': {('bank', 'category')},
            },
        ),
        migrations.CreateModel(
            name='BankCashbackMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('common_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Common monthly limit for this bank', max_digits=15, null=True)),
                ('max_categories', models.PositiveIntegerField(blank=True, default=None, help_text='Max categories to select (defaults to bank limit)', null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_months', to='finance.bank')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('bank', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='BankCashbackSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=True)),
                ('bank_cashback_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.bankcashbackcategory')),
                ('bank_cashback_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='finance.bankcashbackmonth')),
            ],
            options={
                'unique_together': {('bank_cashback_month', 'bank_cashback_category')},
            },
        ),
    ]
