# Generated by Django 6.0.2 on 2026-03-29 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_bank_cashback_categories_limit_bankcashbackcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cashback_categories/')),
                ('waste_category', models.CharField(blank=True, choices=[('PRODUCTS', 'Products'), ('CAFE_AND_RESTAURANTS', 'Cafe and restaurants'), ('TRANSPORT', 'Transport'), ('HCS', 'HCS'), ('HOUSEHOLD', 'Household'), ('PERSONAL', 'Personal'), ('LEISURE', 'Leisure'), ('ENTERTAINMENT', 'Entertainment'), ('CLOTHING_AND_SHOES', 'Clothing and shoes'), ('SPORT', 'Sport'), ('HEALTH_AND_BEAUTY', 'Health and beauty'), ('SUBSCRIPTIONS', 'Subscriptions'), ('TAXES_AND_PENALTIES', 'Taxes and penalties'), ('LEARNING', 'Learning'), ('GIFTS', 'Gifts'), ('TECHNIQUE', 'Technique'), ('TRAVELING', 'Traveling'), ('REALTY', 'Realty'), ('OTHER_WASTE', 'Other waste')], help_text='Optional link to waste category', max_length=30, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='bankcashbackcategory',
            options={'ordering': ['category__name']},
        ),
        migrations.AlterField(
            model_name='bankcashbackcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_categories', to='finance.cashbackcategory'),
        ),
    ]
