# Generated by Django 6.0.2 on 2026-03-29 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_add_cashback_category_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCashbackMonthCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('limit', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly limit for this category', max_digits=15, null=True)),
                ('bank_cashback_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_categories', to='finance.bankcashbackmonth')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.cashbackcategory')),
            ],
            options={
                'ordering': ['category__name'],
                'unique_together': {('bank_cashback_month', 'category')},
            },
        ),
    ]
