# Generated by Django 6.0.2 on 2026-05-12 18:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_add_bank_cashback_month_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='commission_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15),
        ),
    ]
