# Generated by Django 6.0.2 on 2026-05-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_alter_transaction_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='exclude_from_stats',
            field=models.BooleanField(default=False),
        ),
    ]
